capture_source_picklist = "Device"
report_sort_type = "Neutral"
host_sort_type = "Neutral"
service_sort_type = "Neutral"
last_opened_setting = "Appearance"
last_opened_page = "Overview"
import_pcap_path = ""

[settings]
color_gradient = "None"
language = "EN"
scale_factor = 1.0
mmdb_country = ""
mmdb_asn = ""
style_path = ""

[settings.notifications]
volume = 60

[settings.notifications.data_notification]
data_repr = "Bytes"
byte_multiple = "KB"
sound = "Pop"
previous_threshold = 800000

[settings.notifications.favorite_notification]
notify_on_favorite = false
sound = "Swhoosh"

[settings.style]
style = "Custom"

[settings.style.name]
custom = "A11yDark"

[device]
device_name = "enp1s0"

[window]
position = [
    1100.0,
    17.0,
]
size = [
    849.0,
    1401.0,
]
thumbnail_position = [
    0.0,
    0.0,
]

[filters]
expanded = false
bpf = ""

[export_pcap]
enabled = false
file_name = "sniffnet.pcap"
directory = "/home/jadencodes"
